# ==================================================================================== #
# APPLICATION CONFIGURATION
# ==================================================================================== #

app:
  corsPattern: http://localhost:3000

# Security
security:
  jwt:
    secret: HUnu6O78pb765-BsaBth-gKbTY6-7B65G68bH8H$$+J-GI
    timeExp: 3600000000

# ==================================================================================== #
# REST SERVICES
# ==================================================================================== #
# Pharmacy minsal source
# ------------------------------ #
pharmacy:
  host: https://farmanet.minsal.cl/
  turns:
    tmpl-url: ${pharmacy.host}/index.php/ws/getLocalesTurnos

