name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Rename Artifact
        run: cp build/libs/ms-pharmacys-turn-1.0.0.jar ms-pharmacys-turn-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: ms-pharmacys-turn
          path: ms-pharmacys-turn-${{ github.sha }}.jar
  deploy-to-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

#      - name: Overwrite Markdown
#        run: |
#          echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
#          echo "There was an error, we need to clear the previous Markdown with some new content." > $GITHUB_STEP_SUMMARY
