name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Rename Artifact
        run: cp build/libs/ms-pharmacys-turn-1.0.0.jar ms-pharmacys-turn-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: ms-pharmacys-turn
          path: ms-pharmacys-turn-${{ github.sha }}.jar

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.1.0
        with:
          project: ${{ secrets.gcp_project }}
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}

      - name: Deploy a Cloud Run service
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v0.1.0
        with:
#          image: gcr.io/cloudrun/hello
          service: pharmacys-turn
          project: ${{ secrets.gcp_project }}
          credentials: ${{ secrets.gcp_credentials }}

#      - name: Overwrite Markdown
#        run: |
#          echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
#          echo "There was an error, we need to clear the previous Markdown with some new content." > $GITHUB_STEP_SUMMARY
